Rollback to old version.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,7 +13,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
       - uses: actions/setup-node@v4
         id: setup-node
@@ -47,23 +47,10 @@ jobs:
       - name: Diff Tokens
         id: diff-tokens
         run: |
-          for filePath in ./tokens/css/variables*.css; do
-            fileName=${filePath/.\/tokens\/css\//}
-            reqStatus=$(curl -sL --write-out "%{http_code}" -o ./tokens/css/${fileName/%.css/.old.css} https://nala.bravesoftware.com/css/$fileName)
-            # Note: Diff has exit code 1 for differences, and there are always
-            # some differences because the file contains a timestamp.
-            if [ -s ./tokens/css/file-sizes.diff ]; then
-              echo "---" >> ./tokens/css/file-sizes.diff
-            fi
-            if [ "$reqStatus" -eq 200 ]; then
-              echo "- $(stat -c "%n: %s bytes" ./tokens/css/${fileName/%.css/.old.css})" >> ./tokens/css/file-sizes.diff
-              echo "+ $(stat -c "%n: %s bytes" ./tokens/css/$fileName)" >> ./tokens/css/file-sizes.diff
-              diff -u ./tokens/css/${fileName/%.css/.old.css} ./tokens/css/$fileName >> ./tokens/css/${fileName/%.css/.diff} || :
-            else
-              echo "+ $(stat -c "%n: %s bytes" ./tokens/css/$fileName)" >> ./tokens/css/file-sizes.diff
-              diff -u /dev/null ./tokens/css/$fileName >> ./tokens/css/${fileName/%.css/.diff} || :
-            fi
-          done
+          curl -fsSL -o ./tokens/css/variables.old.css https://nala.bravesoftware.com/css/variables.css
+          # Note: Diff has exit code 1 for differences, and there are always
+          # some differences because the file contains a timestamp.
+          diff -u ./tokens/css/variables.old.css ./tokens/css/variables.css > ./tokens/css/variables.diff || :
 
       - name: Check Types
         id: check-types
@@ -83,11 +70,10 @@ jobs:
         run: npm run build-storybook
 
       - name: Upload Artifact
-        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
+        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
         with:
           name: build
           if-no-files-found: error
           path: |
             ./storybook-static
-            ./tokens/css/variables*.diff
-            ./tokens/css/file-sizes.diff
+            ./tokens/css/variables.diff
